# Generated by Django 4.2.17 on 2024-12-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
